class OcrLanguage {
  final String code;
  final String name;

  const OcrLanguage(this.code, this.name);

  static const all = <OcrLanguage>[
    OcrLanguage('afr', 'Afrikaans'),
    OcrLanguage('amh', 'Amharic'),
    OcrLanguage('ara', 'Arabic'),
    OcrLanguage('asm', 'Assamese'),
    OcrLanguage('aze', 'Azerbaijani'),
    OcrLanguage('aze_cyrl', 'Azerbaijani (Cyrillic)'),
    OcrLanguage('bel', 'Belarusian'),
    OcrLanguage('ben', 'Bengali'),
    OcrLanguage('bod', 'Tibetan'),
    OcrLanguage('bos', 'Bosnian'),
    OcrLanguage('bre', 'Breton'),
    OcrLanguage('bul', 'Bulgarian'),
    OcrLanguage('cat', 'Catalan'),
    OcrLanguage('ceb', 'Cebuano'),
    OcrLanguage('ces', 'Czech'),
    OcrLanguage('chi_sim', 'Chinese (Simplified)'),
    OcrLanguage('chi_tra', 'Chinese (Traditional)'),
    OcrLanguage('chr', 'Cherokee'),
    OcrLanguage('cym', 'Welsh'),
    OcrLanguage('dan', 'Danish'),
    OcrLanguage('deu', 'German'),
    OcrLanguage('div', 'Dhivehi'),
    OcrLanguage('dzo', 'Dzongkha'),
    OcrLanguage('ell', 'Greek'),
    OcrLanguage('eng', 'English'),
    OcrLanguage('enm', 'English (Middle)'),
    OcrLanguage('epo', 'Esperanto'),
    OcrLanguage('est', 'Estonian'),
    OcrLanguage('eus', 'Basque'),
    OcrLanguage('fao', 'Faroese'),
    OcrLanguage('fas', 'Persian'),
    OcrLanguage('fil', 'Filipino'),
    OcrLanguage('fin', 'Finnish'),
    OcrLanguage('fra', 'French'),
    OcrLanguage('frm', 'French (Middle)'),
    OcrLanguage('fry', 'Frisian'),
    OcrLanguage('gla', 'Scottish Gaelic'),
    OcrLanguage('gle', 'Irish'),
    OcrLanguage('glg', 'Galician'),
    OcrLanguage('grc', 'Greek (Ancient)'),
    OcrLanguage('guj', 'Gujarati'),
    OcrLanguage('hat', 'Haitian'),
    OcrLanguage('heb', 'Hebrew'),
    OcrLanguage('hin', 'Hindi'),
    OcrLanguage('hrv', 'Croatian'),
    OcrLanguage('hun', 'Hungarian'),
    OcrLanguage('hye', 'Armenian'),
    OcrLanguage('iku', 'Inuktitut'),
    OcrLanguage('ind', 'Indonesian'),
    OcrLanguage('isl', 'Icelandic'),
    OcrLanguage('ita', 'Italian'),
    OcrLanguage('jav', 'Javanese'),
    OcrLanguage('jpn', 'Japanese'),
    OcrLanguage('kan', 'Kannada'),
    OcrLanguage('kat', 'Georgian'),
    OcrLanguage('kaz', 'Kazakh'),
    OcrLanguage('khm', 'Khmer'),
    OcrLanguage('kir', 'Kyrgyz'),
    OcrLanguage('kmr', 'Kurdish (Northern)'),
    OcrLanguage('kor', 'Korean'),
    OcrLanguage('lao', 'Lao'),
    OcrLanguage('lat', 'Latin'),
    OcrLanguage('lav', 'Latvian'),
    OcrLanguage('lit', 'Lithuanian'),
    OcrLanguage('ltz', 'Luxembourgish'),
    OcrLanguage('mal', 'Malayalam'),
    OcrLanguage('mar', 'Marathi'),
    OcrLanguage('mkd', 'Macedonian'),
    OcrLanguage('mlt', 'Maltese'),
    OcrLanguage('mon', 'Mongolian'),
    OcrLanguage('mri', 'Māori'),
    OcrLanguage('msa', 'Malay'),
    OcrLanguage('mya', 'Myanmar'),
    OcrLanguage('nep', 'Nepali'),
    OcrLanguage('nld', 'Dutch'),
    OcrLanguage('nor', 'Norwegian'),
    OcrLanguage('oci', 'Occitan'),
    OcrLanguage('ori', 'Odia'),
    OcrLanguage('pan', 'Punjabi'),
    OcrLanguage('pol', 'Polish'),
    OcrLanguage('por', 'Portuguese'),
    OcrLanguage('pus', 'Pashto'),
    OcrLanguage('que', 'Quechua'),
    OcrLanguage('ron', 'Romanian'),
    OcrLanguage('rus', 'Russian'),
    OcrLanguage('san', 'Sanskrit'),
    OcrLanguage('sin', 'Sinhala'),
    OcrLanguage('slk', 'Slovak'),
    OcrLanguage('slv', 'Slovenian'),
    OcrLanguage('spa', 'Spanish'),
    OcrLanguage('sqi', 'Albanian'),
    OcrLanguage('srp', 'Serbian'),
    OcrLanguage('srp_latn', 'Serbian (Latin)'),
    OcrLanguage('swa', 'Swahili'),
    OcrLanguage('swe', 'Swedish'),
    OcrLanguage('syr', 'Syriac'),
    OcrLanguage('tam', 'Tamil'),
    OcrLanguage('tel', 'Telugu'),
    OcrLanguage('tgk', 'Tajik'),
    OcrLanguage('tha', 'Thai'),
    OcrLanguage('tir', 'Tigrinya'),
    OcrLanguage('tur', 'Turkish'),
    OcrLanguage('uig', 'Uyghur'),
    OcrLanguage('ukr', 'Ukrainian'),
    OcrLanguage('urd', 'Urdu'),
    OcrLanguage('uzb', 'Uzbek'),
    OcrLanguage('uzb_cyrl', 'Uzbek (Cyrillic)'),
    OcrLanguage('vie', 'Vietnamese'),
    OcrLanguage('yid', 'Yiddish'),
  ];
}
